"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ME = exports.INVOICE_ADDED = exports.REMOVE_INVOICE = exports.GET_INVOICE_BY_ID = exports.ALL_INVOICES = exports.CREATE_USER = exports.EDIT_INVOICE = exports.ADD_INVOICE = exports.INVOICE_DETAILS = exports.SENDER_INFO = exports.CLIENT_INFO = void 0;
var client_1 = require("@apollo/client");
exports.CLIENT_INFO = (0, client_1.gql)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    fragment ClientInfo on ClientAddress {\n        city,\n        country,\n        postCode\n        street\n    }\n"], ["\n    fragment ClientInfo on ClientAddress {\n        city,\n        country,\n        postCode\n        street\n    }\n"])));
exports.SENDER_INFO = (0, client_1.gql)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    fragment SenderInfo on SenderAddress {\n        city,\n        country,\n        postCode\n        street\n    }\n"], ["\n    fragment SenderInfo on SenderAddress {\n        city,\n        country,\n        postCode\n        street\n    }\n"])));
exports.INVOICE_DETAILS = (0, client_1.gql)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  fragment InvoiceDetails on Invoice {\n      clientAddress {\n          city\n          country\n          postCode\n          street\n      }\n      clientEmail\n      clientName\n      createdAt\n      description\n      id\n      items {\n          id\n          name\n          price\n          quantity\n          total\n      }\n      paymentDue\n      paymentTerms\n      senderAddress {\n          city\n          country\n          postCode\n          street\n      }\n      status\n      total\n  }\n"], ["\n  fragment InvoiceDetails on Invoice {\n      clientAddress {\n          city\n          country\n          postCode\n          street\n      }\n      clientEmail\n      clientName\n      createdAt\n      description\n      id\n      items {\n          id\n          name\n          price\n          quantity\n          total\n      }\n      paymentDue\n      paymentTerms\n      senderAddress {\n          city\n          country\n          postCode\n          street\n      }\n      status\n      total\n  }\n"])));
exports.ADD_INVOICE = (0, client_1.gql)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    mutation addInvoice(\n        $clientEmail: String,\n        $clientAddress: ClientAddress,\n        $clientName: String,\n        $createdAt: String,\n        $description: String,\n        $id: String,\n        $items: [Item],\n        $paymentDue: String,\n        $paymentTerms: Float,\n        $senderAddress: SenderAddress,\n        $status: String,\n        $total: Float\n    ) {\n      addInvoice(\n       clientEmail: $clientEmail,\n        clientAddress: $clientAddress,\n        clientName: $clientName,\n        createdAt: $createdAt,\n        description: $description,\n        id: $id,\n        items: $items,\n        paymentDue: $paymentDue,\n        paymentTerms: $paymentTerms,\n        senderAddress: $senderAddress,\n        status: $status,\n        total: $total\n      )\n    }\n"], ["\n    mutation addInvoice(\n        $clientEmail: String,\n        $clientAddress: ClientAddress,\n        $clientName: String,\n        $createdAt: String,\n        $description: String,\n        $id: String,\n        $items: [Item],\n        $paymentDue: String,\n        $paymentTerms: Float,\n        $senderAddress: SenderAddress,\n        $status: String,\n        $total: Float\n    ) {\n      addInvoice(\n       clientEmail: $clientEmail,\n        clientAddress: $clientAddress,\n        clientName: $clientName,\n        createdAt: $createdAt,\n        description: $description,\n        id: $id,\n        items: $items,\n        paymentDue: $paymentDue,\n        paymentTerms: $paymentTerms,\n        senderAddress: $senderAddress,\n        status: $status,\n        total: $total\n      )\n    }\n"])));
exports.EDIT_INVOICE = (0, client_1.gql)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  mutation editInvoice($clientAddress: ClientInfo, $clientEmail: String, $clientName: String, $createdAt: String, $description: String, $editInvoiceId: String, $items: [ItemInput], $paymentDue: String, $paymentTerms: Float, $senderAddress: SenderInfo, $status: String, $total: Float) {\n  editInvoice(clientAddress: $clientAddress, clientEmail: $clientEmail, clientName: $clientName, createdAt: $createdAt, description: $description, id: $editInvoiceId, items: $items, paymentDue: $paymentDue, paymentTerms: $paymentTerms, senderAddress: $senderAddress, status: $status, total: $total) {\n    clientAddress {\n      city\n      country\n      postCode\n      street\n    }\n    clientEmail\n    clientName\n    createdAt\n    description\n    id\n    items {\n      id\n      name\n      price\n      quantity\n      total\n    }\n    paymentDue\n    paymentTerms\n    senderAddress {\n      city\n      country\n      postCode\n      street\n    }\n    status\n    total\n  }\n}\n"], ["\n  mutation editInvoice($clientAddress: ClientInfo, $clientEmail: String, $clientName: String, $createdAt: String, $description: String, $editInvoiceId: String, $items: [ItemInput], $paymentDue: String, $paymentTerms: Float, $senderAddress: SenderInfo, $status: String, $total: Float) {\n  editInvoice(clientAddress: $clientAddress, clientEmail: $clientEmail, clientName: $clientName, createdAt: $createdAt, description: $description, id: $editInvoiceId, items: $items, paymentDue: $paymentDue, paymentTerms: $paymentTerms, senderAddress: $senderAddress, status: $status, total: $total) {\n    clientAddress {\n      city\n      country\n      postCode\n      street\n    }\n    clientEmail\n    clientName\n    createdAt\n    description\n    id\n    items {\n      id\n      name\n      price\n      quantity\n      total\n    }\n    paymentDue\n    paymentTerms\n    senderAddress {\n      city\n      country\n      postCode\n      street\n    }\n    status\n    total\n  }\n}\n"])));
exports.CREATE_USER = (0, client_1.gql)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n    mutation CreateUser($username: String!, $password: String!, $name: String) {\n        createUser(username: $username, password: $password, name: $name) {\n            username\n            id\n        }\n    }\n"], ["\n    mutation CreateUser($username: String!, $password: String!, $name: String) {\n        createUser(username: $username, password: $password, name: $name) {\n            username\n            id\n        }\n    }\n"])));
// export const ALL_INVOICES = gql`
//   query allInvoices {
//       senderAddress {
//           ...SenderInfo
//       }
//       clientAddress {
//           ...ClientInfo,
//       }
//       clientEmail,
//       clientName,
//       createdAt,
//       description,
//       id,
//       items,
//       paymentDue,
//       paymentTerms,
//       status,
//       total
//   }
//   ${SENDER_INFO}
//   ${CLIENT_INFO}
//
// `;
exports.ALL_INVOICES = (0, client_1.gql)(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n\n    query allInvoices {\n        allInvoices {\n            clientAddress {\n                city\n                country\n                postCode\n                street\n            }\n            clientEmail\n            clientName\n            createdAt\n            description\n            id\n            items {\n                id\n                name\n                price\n                quantity\n                total\n            }\n            paymentDue\n            paymentTerms\n            senderAddress {\n                city\n                country\n                postCode\n                street\n            }\n            status\n            total\n        }\n    }"], ["\n\n    query allInvoices {\n        allInvoices {\n            clientAddress {\n                city\n                country\n                postCode\n                street\n            }\n            clientEmail\n            clientName\n            createdAt\n            description\n            id\n            items {\n                id\n                name\n                price\n                quantity\n                total\n            }\n            paymentDue\n            paymentTerms\n            senderAddress {\n                city\n                country\n                postCode\n                street\n            }\n            status\n            total\n        }\n    }"])));
exports.GET_INVOICE_BY_ID = (0, client_1.gql)(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n    query GetInvoiceById($getInvoiceByIdId: String!) {\n        getInvoiceById(id: $getInvoiceByIdId) {\n            clientAddress {\n                city\n                country\n                postCode\n                street\n            }\n            clientEmail\n            clientName\n            createdAt\n            description\n            id\n            items {\n                id\n                name\n                price\n                quantity\n                total\n            }\n            paymentDue\n            paymentTerms\n            senderAddress {\n                city\n                country\n                postCode\n                street\n            }\n            status\n            total\n        }\n    }\n\n"], ["\n    query GetInvoiceById($getInvoiceByIdId: String!) {\n        getInvoiceById(id: $getInvoiceByIdId) {\n            clientAddress {\n                city\n                country\n                postCode\n                street\n            }\n            clientEmail\n            clientName\n            createdAt\n            description\n            id\n            items {\n                id\n                name\n                price\n                quantity\n                total\n            }\n            paymentDue\n            paymentTerms\n            senderAddress {\n                city\n                country\n                postCode\n                street\n            }\n            status\n            total\n        }\n    }\n\n"])));
exports.REMOVE_INVOICE = (0, client_1.gql)(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n    mutation RemoveInvoice($removeInvoiceId: String!) {\n        removeInvoice(id: $removeInvoiceId)\n    }\n"], ["\n    mutation RemoveInvoice($removeInvoiceId: String!) {\n        removeInvoice(id: $removeInvoiceId)\n    }\n"])));
exports.INVOICE_ADDED = (0, client_1.gql)(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n    subscription {\n        invoiceAdded {\n            ...InvoiceDetails\n        }\n    }\n    ", "\n"], ["\n    subscription {\n        invoiceAdded {\n            ...InvoiceDetails\n        }\n    }\n    ", "\n"])), exports.INVOICE_DETAILS);
exports.ME = (0, client_1.gql)(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n    query {\n        me {\n            username\n        }\n    }\n"], ["\n    query {\n        me {\n            username\n        }\n    }\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11;
