name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "invoice-frontend/**" # Triggers on any changes within the frontend directory
  pull_request:
    branches:
      - main
    paths:
      - "invoice-frontend/**" # Triggers on PRs that modify the frontend directory

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_BACKEND_URL: http://proxy:8000 # This must be updated once I know the URL
      FRONTEND_DIR: invoice-frontend
    strategy:
      matrix:
        node-version: [22.x] # You can adjust the Node.js version if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm ci

      - name: Build the project
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.FRONTEND_DIR }}/dist # Adjust this if your build output directory differs
          # If you want to deploy to a specific branch (e.g., gh-pages), you can specify:
          # publish_branch: gh-pages
